[project]
name = "light-phone-cli-tui"
version = "0.1.1"
description = "Unofficial CLI/TUI for the Light Phone"
authors = [{ name = "Alexis Garado", email = "alexisgarado@proton.me" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click",
    "rich_click",
    "rich",
    "textual",
    "pyperclip",
    "light-phone-api",
]

[project.scripts]
light = "light_cli_tui.cli:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["light_cli_tui"]
