# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: light_daemon/v1/music.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'light_daemon/v1/music.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1blight_daemon/v1/music.proto\x12\x0flight_daemon.v1\"Y\n\x05Track\x12\x10\n\x08\x61udio_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x03 \x01(\t\x12\r\n\x05\x61lbum\x18\x04 \x01(\t\x12\x10\n\x08\x66ilename\x18\x05 \x01(\t\"\x13\n\x11ListTracksRequest\"<\n\x12ListTracksResponse\x12&\n\x06tracks\x18\x01 \x03(\x0b\x32\x16.light_daemon.v1.Track2e\n\x0cMusicService\x12U\n\nListTracks\x12\".light_daemon.v1.ListTracksRequest\x1a#.light_daemon.v1.ListTracksResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'light_daemon.v1.music_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRACK']._serialized_start=48
  _globals['_TRACK']._serialized_end=137
  _globals['_LISTTRACKSREQUEST']._serialized_start=139
  _globals['_LISTTRACKSREQUEST']._serialized_end=158
  _globals['_LISTTRACKSRESPONSE']._serialized_start=160
  _globals['_LISTTRACKSRESPONSE']._serialized_end=220
  _globals['_MUSICSERVICE']._serialized_start=222
  _globals['_MUSICSERVICE']._serialized_end=323
# @@protoc_insertion_point(module_scope)
