# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from light_daemon.v1 import music_pb2 as light__daemon_dot_v1_dot_music__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in light_daemon/v1/music_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MusicServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTracks = channel.unary_unary(
                '/light_daemon.v1.MusicService/ListTracks',
                request_serializer=light__daemon_dot_v1_dot_music__pb2.ListTracksRequest.SerializeToString,
                response_deserializer=light__daemon_dot_v1_dot_music__pb2.ListTracksResponse.FromString,
                _registered_method=True)


class MusicServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListTracks(self, request, context):
        """Return every track currently on the device.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MusicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTracks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTracks,
                    request_deserializer=light__daemon_dot_v1_dot_music__pb2.ListTracksRequest.FromString,
                    response_serializer=light__daemon_dot_v1_dot_music__pb2.ListTracksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'light_daemon.v1.MusicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('light_daemon.v1.MusicService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MusicService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListTracks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/light_daemon.v1.MusicService/ListTracks',
            light__daemon_dot_v1_dot_music__pb2.ListTracksRequest.SerializeToString,
            light__daemon_dot_v1_dot_music__pb2.ListTracksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
