[tool.poetry]
name = "light_api"
version = "0.1.0"
description = "Unofficial API for the Light Phone"
authors = [
  "Alexis Garado <alexisgarado@proton.me>"
]
readme = "README.md"
packages = [{ include = "light_api" }]

[tool.poetry.dependencies]
python = "^3.11"
keyring = "*"
mutagen = "*"
playwright = "*"
light-client = { path = "../light-client", develop = true }

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
