name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: astral-sh/setup-uv@v5

      - name: Build
        run: uv build --all

      - name: Publish
        run: uv publish dist/light_phone_*
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
